### ISSUE TITLE
qtdarktheme install prob

### ISSUE THREAD

**Issue by bernardopg** [rohankishore/CashFlow#2]
May you upload a requirements.txt? Im having some issues with the packages.

Sorry for the bad english!

**Comment by rohankishore** [comment]
Yeah sure!

**Comment by rohankishore** [comment]
Did it! Thanks for trying CashFlow. Have a nice day.

**Comment by bernardopg** [comment]
![image](https://github.com/rohankishore/CashFlow/assets/69475128/f10366e2-3063-46fc-830c-4fffeb0a7b96)
man i dont why but it keep showing that

**Comment by bernardopg** [comment]
i just installed all the packages and it dosent work

**Comment by rohankishore** [comment]
Can you please share your Python version and stuff? It's working perfectly fine for me.

**Comment by bernardopg** [comment]
Python 3.12.1

**Comment by rohankishore** [comment]
What? You meant 2.1? Can you share any screenshots?

**Comment by bernardopg** [comment]
3.12.1

**Comment by rohankishore** [comment]
Right that's the issue. Pyqtdarktheme requires 3.11 or below as of now to work properly. You can just try any other theming libraries now. Maybe qt material widgets, which is also a nice alternative. I'll update the code to support it. Thanks a lot
